name: ETL Workflow

on:
  schedule:
    - cron: '30 12 * * *'  # Esto ejecuta el flujo a las 12:20 UTC, que son las 9:20 AM en Argentina

jobs:
  run_etl:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Especifica la versión de Python que necesitas
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run ETL Process
        env:
          DB_CONNECTION_STRING: ${{ secrets.DB_CONNECTION_STRING }}  # Usa tu secreto aquí
        run: python main.py
